name: Extract ZIP Automatically

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  extract-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract ZIP File
        run: unzip ecommerce-platform.zip -d extracted-folder

      - name: Move Extracted Files
        run: mv extracted-folder/* .

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Extracted ZIP automatically"
          git push
